tap "homebrew/bundle"

# Compact TeX distribution as alternative to the full TeX Live / MacTeX
cask "basictex"
# Virtual Audio Driver
cask "blackhole-16ch"
# Open Source Multimedia Framework
cask "gstreamer-runtime"
# Intercept, modify, replay, save HTTP/S traffic
cask "mitmproxy"
# Break time reminder app
cask "stretchly"
# Open-source code editor
cask "visual-studio-code"
# Gecko based web browser
cask "zen-browser"
vscode "antfu.unocss"
vscode "astro-build.astro-vscode"
vscode "azemoh.one-monokai"
vscode "bierner.lit-html"
vscode "biomejs.biome"
vscode "bradlc.vscode-tailwindcss"
vscode "brenek.kotlin-for-frc"
vscode "charliermarsh.ruff"
vscode "continue.continue"
vscode "crdrost.ktfmt"
vscode "csstools.postcss"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "expo.vscode-expo-tools"
vscode "file-icons.file-icons"
vscode "fwcd.kotlin"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "golang.go"
vscode "gruntfuggly.todo-tree"
vscode "icrawl.discord-vscode"
vscode "ionic.ionic"
vscode "james-yu.latex-workshop"
vscode "josevseb.google-java-format-for-vs-code"
vscode "julialang.language-julia"
vscode "miguelsolorio.symbols"
vscode "ms-playwright.playwright"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode.cpptools"
vscode "pokey.cursorless"
vscode "pokey.parse-tree"
vscode "redhat.java"
vscode "runem.lit-plugin"
vscode "rust-lang.rust-analyzer"
vscode "seatonjiang.gitmoji-vscode"
vscode "streetsidesoftware.code-spell-checker"
vscode "svelte.svelte-vscode"
vscode "tamasfe.even-better-toml"
vscode "unifiedjs.vscode-mdx"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vue.volar"
vscode "wakatime.vscode-wakatime"
vscode "yoavbls.pretty-ts-errors"
