[tools]
# Programming languages/package managers
python = ["latest", "3.11"]
bun = "latest"
node = "lts"
pnpm = "latest"
"pipx:pipx" = "latest"
# For Mise autocomplete
usage = "latest"
# Tools I use
"aqua:atuinsh/atuin" = "latest"
bat = "latest"
ripgrep = "latest"
cargo-binstall = "latest"
"cargo:eza" = "latest"
ruff = "latest"
"pipx:yt-dlp" = "latest"
"pipx:auto-editor" = "latest"
"pipx:poethepoet" = "latest"
zoxide = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
"aqua:supabase/cli" = "latest"
"npm:trash-cli" = "latest"
"npm:@antfu/ni" = "latest"
"pipx:copier" = "latest"
mprocs = "latest"
jq = "latest"
fd = "latest"
gh = "latest"
atlas = "latest"
"pipx:pyright" = "latest"
"aqua:Wilfred/difftastic" = "latest"
"cargo:https://github.com/ThatXliner/rt" = "branch:main"
neovim = "latest"
lazygit = "latest"
"npm:sv" = "latest"
"aqua:dylanaraps/neofetch" = "latest"
zig = "latest"
"pipx:poetry" = "2.1.1"
uv = "latest"
"npm:@elgato/cli" = "latest"
"pipx:open-interpreter" = "latest"
pandoc = "latest"
delta = "latest"

[settings]

[settings.npm]
bun = true
