[tools]
# Programming languages/package managers
python = "latest"
bun = "latest"
node = "24"
pnpm = "latest"
# For Mise autocomplete
usage = "latest"
# Tools I use
"aqua:atuinsh/atuin" = "latest"
bat = "latest"
ripgrep = "latest"
cargo-binstall = "latest"
"cargo:eza" = "latest"
ruff = "latest"
"pipx:poethepoet" = "latest"
zoxide = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
"aqua:supabase/cli" = "latest"
"npm:trash-cli" = "latest"
"npm:@antfu/ni" = "latest"
"pipx:copier" = "latest"
mprocs = "latest"
jq = "latest"
fd = "latest"
gh = "latest"
atlas = "latest"
"pipx:pyright" = "latest"
"aqua:Wilfred/difftastic" = "latest"
"cargo:https://github.com/ThatXliner/rt" = "branch:main"
neovim = "latest"
"npm:sv" = "latest"
"aqua:dylanaraps/neofetch" = "latest"
zig = "latest"
"pipx:poetry" = "2.1.1"
uv = "latest"
"npm:@elgato/cli" = "latest"
pandoc = "latest"
delta = "latest"
poetry = "latest"
"npm:opencommit" = "latest"
"pipx:open-interpreter" = "latest"
ruby = "latest"
"pipx:hy" = "latest"
fzf = "latest"
"pipx:yt-dlp" = { version = "latest", extras = "curl-cffi" }
"pipx:httpie" = "latest"
"pipx:ipython" = { version = "latest", uvx_args = " -w hid -w pyautogui -w sympy -w numpy -w pandas -w matplotlib -w requests -w aiohttp" }
"pipx:ufbt" = "latest"
# "pipx:'git+https://github.com/nari-labs/dia.git'" = { version = "latest", uvx_args = "--python 3.9" }
"pipx:thefuck" = { version = "latest", uvx_args = "--python 3.11" }
"npm:taze" = "latest"
fx = "latest"
"npm:biome" = "latest"
"aqua:schollz/croc" = "latest"
aws = "latest"
"pipx:podman-compose" = "latest"
"npm:@vtsls/language-server" = "latest"
just = "latest"
"pipx:scrapy" = "latest"
"npm:eas-cli" = "latest"
java = "latest"
# "npm:wrangler" = "latest"
"npm:localtunnel" = "latest"
yazi = "latest"
# "npm:vibe-kanban" = "latest"
biome = "latest"
prettier = "latest"
"pipx:llm" = "latest"
zellij = "latest"
"npm:opencode-ai" = "latest"
"npm:@openai/codex" = "latest"

[settings]
idiomatic_version_file_enable_tools = []

[settings.npm]
bun = true
