export EDITOR="/usr/bin/vim"
export PAGER="less -r"
export PIPX_DEFAULT_PYTHON="$HOME/.local/share/mise/installs/python/3.13.0/bin/python"
export PIPX_HOME="$HOME/.local/pipx"
export PYTHONSTARTUP="$HOME/.pythonrc.py"