#!/usr/bin/env bash

install_antidote() {
    git clone --depth=1 https://github.com/mattmc3/antidote.git ${ZDOTDIR:-$HOME}/.antidote
}
reset_zshrc() {
    echo "source $HOME/dotfiles/zshrc/index.zsh" > ~/.zshrc
    source ~/.zshrc
}
do_homebrew() {
    if command -v brew &> /dev/null
    then
        echo "Homebrew already installed"
    else
        echo "Installing homebrew"
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> ~/.zprofile
        eval "$(/opt/homebrew/bin/brew shellenv)"
    fi
    cd ~/dotfiles && brew bundle install
    /opt/homebrew/opt/fzf/install
}
do_pipx() {
    if command -v pipx &> /dev/null
    then
        return
    fi
    pip install pipx
    pipx install pipx
    pip uninstall pipx --yes
    cat $HOME/dotfiles/requirements.txt | xargs -n 1 pipx install
}
install_asdf() {
    git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.13.1
    . "$HOME/.asdf/asdf.sh"  # For now
}
setup_asdf() {
    asdf plugin add python
    asdf install python latest
    asdf global python latest
    asdf install python latest:3.11  # For pipx for now

    asdf plugin add nodejs
    asdf install nodejs latest
    asdf global nodejs latest

    asdf plugin-add direnv
    asdf direnv setup --shell zsh --version system
    asdf global direnv system
}
do_js_stuff() {
    curl -fsSL https://get.pnpm.io/install.sh | sh -
    curl -fsSL https://bun.sh/install | bash
    pnpm install -g node-gyp  # XXX
    pnpm install-completion zsh
    pnpm add -g trash-cli
}
install_rust() {
    # Rustup > asdf
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
}
setup_config() {
    if gum confirm "Should we sign commits with GPG"
    then
        git config --global commit.gpgsign true
        git config --global user.signingkey $(gum input --prompt "Your GPG key ID: " --placeholder "Get it from gpg --list-secret-keys --keyid-format=long")
    fi
    git config --global user.name "$(gum input --prompt "Your Git full name: " --placeholder "John Doe")"
    git config --global user.email "$(gum input --prompt "Your Git email: " --placeholder "(matches the email for GPG key)")"
    # Git aliases
    git config --global alias.aliases 'config --get-regexp alias'
    git config --global alias.abort-merge 'reset --hard HEAD'
    git config --global alias.uncommit 'reset --soft HEAD^'
    git config --global alias.unstage 'reset --'
    git config --global alias.permission-reset '!git diff -p -R --no-ext-diff --no-color --diff-filter=M | grep -E "^(diff|(old|new) mode)" --color=never | git apply'
    # Better default pull behavior
    git config --global pull.rebase true
    git config --global rebase.autoStash true
    # alias.cleanup-branches !curl -s https://raw.githubusercontent.com/paulmillr/dotfiles/master/git-extras/git-cleanup.rb | ruby -
    # alias.reset-to-remote reset --hard @{u}
    # alias.l log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all

    # Use multiline prompt
    ln -sf ~/dotfiles/prompts/multi.zsh ~/.p10k.zsh
    # Setup direnv
    echo "[global]\nload_dotenv = true" > ~/.config/direnv/direnv.toml
    # Setup Vim
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    ln -sf ~/dotfiles/.vimrc ~/.vimrc
}
install_custom_direnv() {
    cd
    git clone https://github.com/ThatXliner/direnv.git ~/temp
    cd ~/temp
    git switch support-extra-env-files
    make
    mkdir -p ~/bin
    cp direnv ~/bin/direnv
    cd ..
    rm -rf ~/temp
    export PATH="$HOME/bin:$PATH"  # For now
}
# TODO: download the visual stuff too
main() {
    # Remove "last login" message
    touch ~/.hushlogin
    # Install Xcode command line tools
    xcode-select --install || echo 'Xcode already set up!'
    if ! command -v gpg
    then
        echo "Please install GPGTools"
        return
    fi
    # Clone my dotfiles
    git clone https://github.com/ThatXliner/dotfiles.git ~/dotfiles

    install_asdf &
    install_antidote &
    wait
    do_homebrew

    gum confirm "Please install Go from https://go.dev before continuing"
    install_custom_direnv
    setup_asdf
    reset_zshrc

    do_pipx &
    do_js_stuff &
    install_rust &
    wait
    reset_zshrc

    setup_config
    reset_zshrc
}
main
